// settings.js
class Settings {
    constructor() {
        this.settings = this.defaultSettings();
        this.listeners = [];
        this.initialized = false;
    }

    defaultSettings() {
        return {
            apiKeys: [],
            currentApiKeyIndex: 0,
            apiEndPoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',
            autoGenerateDescriptions: false,
            autoSaveProduct: false
        };
    }

    async initialize() {
        if (this.initialized) return;

        // Load settings from Chrome sync storage
        await this.loadFromStorage();

        // Save to localStorage for quick access by content scripts
        this.syncToLocalStorage();

        // Listen for changes in other tabs
        this.setupChangeListener();

        this.initialized = true;
    }

    async loadFromStorage() {
        try {
            const result = await chrome.storage.sync.get(null);

            // Merge with defaults
            this.settings = {
                ...this.defaultSettings(),
                ...result
            };

            // Also sync to localStorage for content script fallback
            this.syncToLocalStorage();

        } catch (error) {
            console.error('Error loading settings:', error);
        }
    }

    syncToLocalStorage() {
        try {
            console.log('Syncing settings to localStorage:->', this.settings);
            localStorage.setItem('product_descripton_generator_settings', JSON.stringify(this.settings));
        } catch (error) {
            console.warn('Error syncing to localStorage:', error);
        }
    }

    async saveToStorage(settings = null) {
        try {
            if (settings) {
                this.settings = {
                    ...this.settings,
                    ...settings
                };
            }
            console.log('Saving settings to storage:->', this.settings);
            await chrome.storage.sync.set(this.settings);

            // Sync to localStorage for quick access
            this.syncToLocalStorage();

            // Notify all listeners
            this.notifyListeners();

            // Broadcast to other extension contexts
            await this.broadcastSettings();

            return true;
        } catch (error) {
            console.error('Error saving settings:', error);
            return false;
        }
    }

    async broadcastSettings() {
        try {
            // Save to localStorage on all VU tabs
            const tabs = await chrome.tabs.query({ url: 'https://onlinesalepoint.com/shop/products/*/edit' });

            for (const tab of tabs) {
                try {
                    await chrome.scripting.executeScript({
                        target: { tabId: tab.id },
                        func: (settings) => {
                            // Save to localStorage for fallback
                            localStorage.setItem('product_descripton_generator_settings', JSON.stringify(settings));

                            // Broadcast to content scripts
                            chrome.tabs.sendMessage(tab.id, {
                                type: 'settings',
                                settings
                            });
                        },
                        args: [this.settings]
                    });
                } catch (error) {
                    console.log(`Could not update tab ${tab.id}:`, error.message);
                }
            }
        } catch (error) {
            console.error('Error broadcasting settings:', error);
        }
    }

    setupChangeListener() {
        chrome.storage.onChanged.addListener((changes, area) => {
            if (area === 'sync') {
                Object.keys(changes).forEach(key => {
                    this.settings[key] = changes[key].newValue;
                });

                this.notifyListeners();
            }
        });
    }

    addListener(callback) {
        this.listeners.push(callback);
    }

    removeListener(callback) {
        const index = this.listeners.indexOf(callback);
        if (index > -1) {
            this.listeners.splice(index, 1);
        }
    }

    notifyListeners() {
        this.listeners.forEach(callback => {
            try {
                callback(this.settings);
            } catch (error) {
                console.error('Error in settings listener:', error);
            }
        });
    }

    get(key) {
        return this.settings[key];
    }

    set(key, value) {
        this.settings[key] = value;
        return this.saveToStorage({ [key]: value });
    }

    getAll() {
        return { ...this.settings };
    }

    resetToDefaults() {
        this.settings = this.defaultSettings();
        return this.saveToStorage();
    }

    // API Key management methods
    addApiKey(apiKey) {
        if (!apiKey || this.settings.apiKeys.includes(apiKey)) {
            return false;
        }
        this.settings.apiKeys.push(apiKey);
        if (this.settings.apiKeys.length === 1) {
            this.settings.currentApiKeyIndex = 0;
        }
        return this.saveToStorage({
            apiKeys: this.settings.apiKeys,
            currentApiKeyIndex: this.settings.currentApiKeyIndex
        });
    }

    removeApiKey(index) {
        if (index >= 0 && index < this.settings.apiKeys.length) {
            this.settings.apiKeys.splice(index, 1);
            if (this.settings.currentApiKeyIndex >= this.settings.apiKeys.length) {
                this.settings.currentApiKeyIndex = Math.max(0, this.settings.apiKeys.length - 1);
            }
            return this.saveToStorage({
                apiKeys: this.settings.apiKeys,
                currentApiKeyIndex: this.settings.currentApiKeyIndex
            });
        }
        return false;
    }

    getCurrentApiKey() {
        if (this.settings.apiKeys.length === 0) return null;
        return this.settings.apiKeys[this.settings.currentApiKeyIndex];
    }

    rotateToNextApiKey() {
        if (this.settings.apiKeys.length <= 1) return false;
        this.settings.currentApiKeyIndex = (this.settings.currentApiKeyIndex + 1) % this.settings.apiKeys.length;
        return this.saveToStorage({ currentApiKeyIndex: this.settings.currentApiKeyIndex });
    }

    getApiKeys() {
        return [...this.settings.apiKeys];
    }

    getCurrentApiKeyIndex() {
        return this.settings.currentApiKeyIndex;
    }
}

export default Settings;